# Generated by Django 4.0.1 on 2022-01-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('firstName', models.TextField(default='Enter first name... ', max_length=15)),
                ('lastName', models.TextField(default='Enter last name... ', max_length=15)),
                ('studentEmail', models.EmailField(blank=True, max_length=254)),
                ('studentAge', models.PositiveSmallIntegerField(default='Enter student age... ', max_length=2)),
                ('studentGrade', models.IntegerField(default='Enter student grade... ', max_length=1)),
            ],
        ),
    ]
